In [1]:
import torch

In [2]:
# Construct a 5x3 matrix, uninitialized.
x = torch.empty(5, 3)
print(x)

tensor([[-2.8770e+28,  4.5814e-41, -2.8770e+28],
        [ 4.5814e-41,  6.4839e-10,  4.1654e-11],
        [ 2.6076e-09,  2.9575e-18,  6.7333e+22],
        [ 1.7591e+22,  1.7184e+25,  4.3222e+27],
        [ 6.1972e-04,  7.2443e+22,  1.7728e+28]])


In [3]:
print(x.size())

# torch.Size is in fact a tuple.

torch.Size([5, 3])


### Operations

In [4]:
# Resizing: if you want to resize/reshape tensor, you can use torch.view:

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [5]:
# If you have a one element tensor, use .item() to get the value as a Python number.
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.4323])
0.43225955963134766


### Numpy bridge

Converting a Torch Tensor to a Numpy array and vice versa is a breeze.

The Torch Tensor and Numpy array will share their underlying memory locations, and changing one will change the other.

In [6]:
# Converting a Torch Tensor to a Numpy Array
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [7]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [8]:
# See how the numpy array changed in value.
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [9]:
# Converting Numpy array to Torch Tensor
# See how changing the np array changed the Torch Tensor automatically

import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors

Tensors can be moved onto any device using the ```.to``` method.

In [16]:
# we will use torch.device object to move tensors in and out of GPU
if torch.cuda.is_available:
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu"), torch.double)

tensor([0.0392], device='cuda:0')
tensor([0.0392]) torch.float64
